import Image from "next/image";
import { Inter } from "next/font/google";
import { FaCopy, FaRegCopy, FaTelegramPlane, FaTwitter } from "react-icons/fa";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={`${inter.className}`}>
      <Head>
        <title> SEZINU</title>
        <meta name="description" content="Generated by SEZINU" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <header className="w-full flex justify-between px-5 py-3 border-b-[0.5px] border-gray-600 bg-[#080808]">
        <span className="flex items-center gap-3">
          <img src="/logo.png" className="w-12" />
          <h4>SEZINU</h4>
        </span>
        <span className="flex items-center gap-4">
          <a href="https://t.me/Sizeinutoken">
            <FaTelegramPlane color="#5D6588" size={30} />
          </a>
          <a href="https://x.com/SizeInu">
            <FaTwitter color="#5D6588" size={30} />
          </a>
        </span>
      </header>
      <main className="w-100 px-5 flex justify-center flex-col items-center py-0 bg-[#080808]">
        <img src="/slider.png" className="w-[220px] md:w-[260px]" />
        <h1 className="text-center mt-12 text-7xl font-mono">SEZINU COIN</h1>
        <p className="mt-3 text-[#999]">Make Memecoins Great Again</p>
        <div className="w-[350px] mx-auto px-6 py-8 bg-[#161820] rounded-lg mt-5 relative">
          <span>CA:</span>
          <span className="ps-2 text-orange-600"> 0xC8c3ae87AfAA5D00b...</span>
          <FaRegCopy className="absolute right-3 top-3" />
        </div>
        <div className="w-100 py-8 m-0 flex justify-center gap-4">
          <button className="btn_btn">
            <span>BUY SEZINU</span>
          </button>
          <button className="btn_btn">
            <span>Chart</span>
          </button>
        </div>
      </main>
      <footer className="bg-black py-12">
        <p className="text-center px-20 text-xl text-[#bababa]">
          Inspired by Founder Arbitrum and the Shiba inu dog. Size inu is a
          memecoin with no intrinsic value or expectation of financial return.
          There is no formal team or roadmap. The coin is completely useless and
          for entertainment purposes only.
        </p>
      </footer>
    </div>
  );
}
